umbrella_core:
    webpack:
        dev_server_enable: false
        dev_server_host: http://127.0.0.1
        dev_server_port: 9000
    form:
        enable_extension: true
    file:
        asset_path: /uploads/
    mailer:
        from: 'no-reply@6tm.com'
    redis:
        host: 127.0.0.1
        port: 6379
        db: 0

twig:
    form_themes:
        - 'UmbrellaCoreBundle:Form:layout.html.twig'
        - 'UmbrellaCoreBundle:Form:layout_vertical.html.twig'