services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # ---- Component ---- #

    # Menu
    Umbrella\CoreBundle\Component\Menu\MenuProvider:
        public: true
    Umbrella\CoreBundle\Component\Menu\MenuRendererProvider:
        public: true
    Umbrella\CoreBundle\Component\Menu\MenuAuthorizationChecker:
        $tokenStorage: "@security.token_storage"
        $language: "@security.expression_language"
        $trustResolver: "@security.authentication.trust_resolver"
        $authChecker: "@security.authorization_checker"
        $roleHierarchy: "@security.role_hierarchy"
    Umbrella\CoreBundle\Component\Menu\MenuHelper:
        public: true
    Umbrella\CoreBundle\Component\Menu\Extension\MenuTwigExtension:
    Umbrella\CoreBundle\Component\Menu\Extension\BreadcrumbTwigExtension:


    # JsResponse
    Umbrella\CoreBundle\Component\JsResponse\JsResponseBuilder:
        public: true

    # DataTable
    Umbrella\CoreBundle\Component\DataTable\DataTableFactory:
        public: true
    Umbrella\CoreBundle\Component\DataTable\ColumnFactory:
        public: true
    Umbrella\CoreBundle\Component\DataTable\Extension\DataTableTwigExtension:

    # Column
    Umbrella\CoreBundle\Component\Column\ActionColumnType:
    Umbrella\CoreBundle\Component\Column\BadgeColumnType:
    Umbrella\CoreBundle\Component\Column\ActiveColumnType:
    Umbrella\CoreBundle\Component\Column\BooleanColumnType:
    Umbrella\CoreBundle\Component\Column\ImageColumnType:
        $cacheManager: "@liip_imagine.cache.manager"

    # Toolbar
    Umbrella\CoreBundle\Component\Toolbar\ToolbarFactory:
        public: true
    Umbrella\CoreBundle\Component\Toolbar\ActionFactory:
        public: true
    Umbrella\CoreBundle\Component\Toolbar\Extension\ToolbarTwigExtension:

    # DateTime
    Umbrella\CoreBundle\Component\DateTime\DateTimeHelper:
        public: true
    Umbrella\CoreBundle\Component\DateTime\DateTimeFormatter:
    Umbrella\CoreBundle\Component\DateTime\DateTimeExtension:

    # Row Action
    Umbrella\CoreBundle\Component\RowAction\UmbrellaRowActionRenderer:

    # ---- Umbrella ----#

    #Command
    Umbrella\CoreBundle\Command\IndexEntityCommand:

    #Extension
    Umbrella\CoreBundle\Extension\CoreTwigExtension:
    Umbrella\CoreBundle\Extension\WebpackTwigExtension:

    #Form
    Umbrella\CoreBundle\Form\:
        resource: '../../Form'

    # Services
    Umbrella\CoreBundle\Services\UmbrellaFileUploader:
        public: true
        bind:
            $publicPath: "%kernel.project_dir%/public"
            $assetPath: "/umbrella-file"

    Umbrella\CoreBundle\Services\SearchHandler:
        public: true
    Umbrella\CoreBundle\Services\UmbrellaRedis:
        public: true
    Umbrella\CoreBundle\Services\EntityIndexer:
        public: true
    Umbrella\CoreBundle\Services\DateFormater:
        public: true
    Umbrella\CoreBundle\Services\Mailer:
        public: true

    # Annotation
    Umbrella\CoreBundle\Annotation\SearchableAnnotationReader:

    # Validator
    Umbrella\CoreBundle\Validator\UmbrellaFileValidator:

    # Listener
    Umbrella\CoreBundle\Listener\EntitySubscriber:
        tags:
            - {name: doctrine.event_subscriber}
    Umbrella\CoreBundle\Listener\UmbrellaFileListener:
        tags:
            - { name: doctrine.orm.entity_listener }
    Umbrella\CoreBundle\Listener\UmbrellaViewResponseListener:
        tags:
            - {name: kernel.event_subscriber }
