services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # ---- Component ---- #

    # Menu
    Umbrella\CoreBundle\Component\Menu\MenuFactory:
    Umbrella\CoreBundle\Component\Menu\MenuProvider:
        public: true
        bind:
            $defaultAlias: "%umbrella_core.menu.default_alias%"
    Umbrella\CoreBundle\Component\Menu\MenuAuthorizationChecker:
        $tokenStorage: "@security.token_storage"
        $language: "@security.expression_language"
        $trustResolver: "@security.authentication.trust_resolver"
        $authChecker: "@security.authorization_checker"
        $roleHierarchy: "@security.role_hierarchy"
    Umbrella\CoreBundle\Component\Menu\MenuHelper:
        public: true
    Umbrella\CoreBundle\Component\Menu\Extension\MenuTwigExtension:


    # JsResponse
    Umbrella\CoreBundle\Component\JsResponse\JsResponseBuilder:
        public: true

    # DataTable
    Umbrella\CoreBundle\Component\DataTable\DataTableFactory:
        public: true
    Umbrella\CoreBundle\Component\DataTable\Extension\DataTableTwigExtension:
    Umbrella\CoreBundle\Component\DataTable\RowAction\RowActionRenderer:

    # Column
    Umbrella\CoreBundle\Component\Column\Type\CheckBoxColumnType:
    Umbrella\CoreBundle\Component\Column\Type\ToggleColumnType:
    Umbrella\CoreBundle\Component\Column\Type\ActionColumnType:
    Umbrella\CoreBundle\Component\Column\Type\BadgeColumnType:
    Umbrella\CoreBundle\Component\Column\Type\ActiveColumnType:
    Umbrella\CoreBundle\Component\Column\Type\BooleanColumnType:
    Umbrella\CoreBundle\Component\Column\Type\ImageColumnType:
        $cacheManager: "@liip_imagine.cache.manager"
    Umbrella\CoreBundle\Component\Column\ColumnFactory:
        public: true

    # Toolbar
    Umbrella\CoreBundle\Component\Toolbar\ToolbarFactory:
        public: true
    Umbrella\CoreBundle\Component\Toolbar\Extension\ToolbarTwigExtension:

    # Action
    Umbrella\CoreBundle\Component\Action\Type\DropdownActionType:
    Umbrella\CoreBundle\Component\Action\Extension\ActionTwigExtension:
    Umbrella\CoreBundle\Component\Action\ActionFactory:
        public: true
    Umbrella\CoreBundle\Component\Action\ActionListFactory:
        public: true

    # Toast
    Umbrella\CoreBundle\Component\Toast\ToastFactory:
        public: true

    # DateTime
    Umbrella\CoreBundle\Component\DateTime\DateTimeHelper:
        public: true
    Umbrella\CoreBundle\Component\DateTime\DateTimeFormatter:
    Umbrella\CoreBundle\Component\DateTime\DateTimeExtension:

    # Schedule
    Umbrella\CoreBundle\Component\Schedule\Command\ScheduleListCommand:
    Umbrella\CoreBundle\Component\Schedule\Command\ScheduleRunCommand:
    Umbrella\CoreBundle\Component\Schedule\Command\TaskRunCommand:
    Umbrella\CoreBundle\Component\Schedule\Runner\Runner:
    Umbrella\CoreBundle\Component\Schedule\Extension\ScheduleExtension:
    Umbrella\CoreBundle\Component\Schedule\RuntimeEnv\EnvironmentProvider:
    Umbrella\CoreBundle\Component\Schedule\Task\TaskFactory:
    Umbrella\CoreBundle\Component\Schedule\JobManager:
    Umbrella\CoreBundle\Component\Schedule\JobHelper:
    Umbrella\CoreBundle\Component\Schedule\Scheduler:
        public : true
        bind:
            $consolePath: "%kernel.project_dir%/bin/console"

    # Ckeditor
    Umbrella\CoreBundle\Component\Ckeditor\CkeditorConfiguration:
    Umbrella\CoreBundle\Component\Ckeditor\CkeditorExtension:

    # Tabs
    Umbrella\CoreBundle\Component\Tabs\TabsHelper:
        bind:
            $configPath: "%kernel.project_dir%/vendor/umbrella/corebundle/Component/Tabs/config.yml"
    Umbrella\CoreBundle\Component\Tabs\TabsExtension:

    # ---- Umbrella ----#

    #Command
    Umbrella\CoreBundle\Command\IndexEntityCommand:

    #Extension
    Umbrella\CoreBundle\Extension\CoreTwigExtension:
    Umbrella\CoreBundle\Extension\WebpackTwigExtension:

    #Form
    Umbrella\CoreBundle\Form\:
        resource: '../../Form'

    # Services
    Umbrella\CoreBundle\Services\UmbrellaFileUploader:
        public: true
        bind:
            $publicPath: "%kernel.project_dir%/public"
            $assetPath: "/umbrella-file"

    Umbrella\CoreBundle\Services\SearchHandler:
        public: true
    Umbrella\CoreBundle\Services\UmbrellaRedis:
        public: true
    Umbrella\CoreBundle\Services\EntityIndexer:
        public: true
    Umbrella\CoreBundle\Services\DateFormater:
        public: true
    Umbrella\CoreBundle\Services\Mailer:
        public: true

    # Annotation
    Umbrella\CoreBundle\Annotation\SearchableAnnotationReader:
    Umbrella\CoreBundle\Annotation\DiscriminatorEntryReader:

    # Validator
    Umbrella\CoreBundle\Validator\UmbrellaFileValidator:

    # Listener

    Umbrella\CoreBundle\Listener\EntitySubscriber:
        tags:
            - {name: doctrine.event_subscriber}
    Umbrella\CoreBundle\Listener\UmbrellaFileListener:
        tags:
            - { name: doctrine.orm.entity_listener }
    Umbrella\CoreBundle\Listener\UmbrellaViewResponseListener:
        tags:
            - {name: kernel.event_subscriber }
